import type { Metadata } from "next";
import { Jost, Nunito } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/Components/Shared/LayoutWrapper";
import { Toaster } from "react-hot-toast";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "VLADIMIRAC",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jost.variable} ${nunito.variable}`}>
      <body className="bg-[#13213C]">
        <Toaster position="top-right" reverseOrder={false} />{" "}
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
