import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import type { Metadata } from "next";
import { Jost, Nunito } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/Components/Shared/LayoutWrapper";
import { Toaster } from "react-hot-toast";

// Google fonts
const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "SavaLogistics",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.png",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${jost.variable} ${nunito.variable}`}>
      <body className="bg-[#13213C]">
        <Toaster position="top-right" reverseOrder={false} />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LayoutWrapper>{children}</LayoutWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
